kanban-todo app/website/views.py
from flask import Blueprint,render_template,request,flash,jsonify,redirect,url_for
from flask_login import login_user,logout_user,current_user
from flask_login import login_required
from .models import User,Note
from . import db
from datetime import date,datetime
import json
from sqlalchemy import func, text

views = Blueprint('views', __name__)

@views.route('/',methods=['GET','POST'])
@login_required
def home():
    if request.method=='POST':
        id1=request.form.get('id')
        title1 = request.form.get('title')
        info = request.form.get('info')
        username= request.form.get('username')
        stat=request.form.get('status')
        deadl=request.form.get('deadline')
        date=request.form.get('date')
        if len(title1)<1:
            flash("title is too short",category="error")
        else:
            new_note=Note(id=id1,title=title1,content=info,user_id=current_user.id,user_name=username,status=stat,deadline=deadl)
            db.session.add(new_note)
            db.session.commit()
            flash("Note added",category="success")
    notes=Note.query.filter_by(user_id=current_user.id).all()
    return render_template("home.html",user=current_user)

@views.route('/add',methods=['GET','POST'])
@login_required
def add(): 
    if request.method=='POST':
        id1=request.form.get('id')
        title1 = request.form.get('title')
        info = request.form.get('info')
        username= request.form.get('username')
        stat=request.form.get('status')
        deadl=request.form.get('deadline')
        date=request.form.get('date')
        comm='NA'
        if len(title1)<1:
            flash("title is too short",category="error")
        else:
            new_note=Note(id=id1,title=title1,content=info,user_id=current_user.id,user_name=username,status=stat,deadline=deadl,com=comm)
            db.session.add(new_note)
            db.session.commit()
            flash("Note added",category="success")
    return render_template("add.html",user=current_user)

@views.route('/about',methods=['GET','POST'])
@login_required
def about(): 
    return render_template("about.html",user=current_user)
    
@views.route('/summary',methods=['GET','POST'])
@login_required
def sum(): 
    com=0
    req=0
    rev=0
    inp=0
    cross=0
    notes=Note.query.filter_by(user=current_user).all()
    today=date.today()
    
    for l in notes:
        x=date(int(l.deadline[0:4]),int(l.deadline[5:7]),int(l.deadline[8:10]))
        
        if l.status=='completed':
            com+=1
            
        elif l.status=='request':
            req+=1
        elif l.status=='review':
            rev+=1
        else:
            inp+=1
        if x<today:
            cross=cross+1
        db.session.commit()
    data = {'Task' : 'Status', 'In Request' : req, 'In Progress' : inp, 'In Review' : rev, 'Completed' : com }
    return render_template("summary.html",user=current_user,comp=com,inp=inp,req=req,rev=rev,cross=cross,data=data)


@views.route('/<int:id>')
@login_required
def delete(id):
    user_to=Note.query.get_or_404(id)
    try:
        db.session.delete(user_to)
        db.session.commit()
        flash("LIST deleted",category="success")
        return render_template("home.html",user=current_user)
    except:
        flash("LIST not deleted",category="error")
        return render_template("home.html",user=current_user)

@views.route('/more/<int:id>',methods=['GET','POST'])
@login_required
def more(id):
    id1=id
    user_to=Note.query.get_or_404(id1) 
    if request.method=='POST':
        if len(request.form.get('comment'))>0:

            user_to.com=request.form.get('comment')
            user_to.date=datetime.now()
        if len(request.form.get('ip'))>0:
            user_to.title=request.form.get('ip')
            user_to.date=datetime.now()
    db.session.commit()
    return render_template("more.html",user=current_user,id=id1,date=date)




@views.route('/update/<int:id>',methods=['GET','POST'])
@login_required
def edit(id):
    id1=id
    stats="request"
    user_to=Note.query.get_or_404(id1) 
    if user_to.status=="completed":
        stats="review"
    user_to.status=stats
    db.session.commit()
    
    return render_template("home.html",user=current_user)

@views.route('/update1/<int:id>',methods=['GET','POST'])
@login_required
def forw(id):
    id1=id
    
    user_to=Note.query.get_or_404(id1) 
    if user_to.status=="review":
        user_to.status="completed"
        
        user_to.timerem =datetime.today()
        now=datetime.now()
        user_to.time= now.strftime("%H:%M:%S")
        
        
    elif user_to.status=="request":
        user_to.status="in progress"
    elif user_to.status=="in progress":
        user_to.status="review"    
            
    db.session.commit()
    return render_template("home.html",user=current_user,t=user_to.timerem,time=user_to.time)


@views.route('/update2/<int:id>',methods=['GET','POST'])
@login_required
def back(id):
    id1=id
    user_to=Note.query.get_or_404(id1) 
    if user_to.status=="review":
        user_to.status="in progress"
    elif user_to.status=="in progress":
        user_to.status="request"
    elif user_to.status=="completed":
        user_to.status="review"    
                
    db.session.commit()
    return redirect("/")

kanban-todo app/website/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <link rel="stylesheet"  href="/static/addstyle.css">
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous"
  />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class=" navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" >
            <span class="navbar-toggler-icon"></span>
        </button>
    
    <div class="collapse navbar-collapse " id="navbar">
      <div class="navbar-nav">
        {%if user.is_authenticated%}
                <a class="nav-item nav-link" id="home" href="/">Home</a>    
                <a class="nav-item nav-link" id="home" href="/add">Add Details</a>
                <a class="nav-item nav-link" id="login" href="/summary">Summary</a>
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
            {%endif%}
        
      </div>
    </div>
    </nav>
   <br>
   <br>
   <div class="container">
    <div class="text">This Website Is Developed By</div>
    <form action="#">
       <div class="form-row">
          <div class="input-data">
             <label for="">Name:&nbsp;&nbsp;RAM PRASATH K</label>
          </div>
          <div class="input-data">
            <label for="">Roll No:&nbsp;&nbsp;21f1002753</label>
          </div>
          <div class="input-data">
            <label for="">Education Details:&nbsp;&nbsp;Completed B.Tech Mechanical , Pursuing Diploma in B.Sc.Data Science and Applications </label>
         </div>
         <div class="input-data">
          <label for="">Contact Email:&nbsp;&nbsp;21f1002753@student.onlinedegree.iitm.ac.in (or) ramkan103@gmail.com</label>
          
        </div>
        
       </div>
       
 </div>
 

</body>
</html>

kanban-todo app/website/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous"
  />
    <title>
        {% block title %}home{% endblock %}
    </title>
    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class=" navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" >
            <span class="navbar-toggler-icon"></span>
        </button>
    
    <div class="collapse navbar-collapse " id="navbar">
      <div class="navbar-nav">
        {%if user.is_authenticated%}
        <a class="nav-item nav-link" id="home" href="/">Home</a>
        
        <a class="nav-item nav-link" id="login" href="/summary">Summary</a>
        <a class="nav-item nav-link" id="signUp" href="/about">About</a>
		<a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
        {%endif%}
        
      </div>
    </div>
    </nav>
    <div >
    {%with messages=get_flashed_messages(with_categories=true)%}
    {%if messages%}
      <div class="alert alert-success">
        {%for category, msg in messages%}
          {%if category =='error'%}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
              {{msg}}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {%else%}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
              {{msg}}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
             
            {%endif%}
          {%endfor%}
        </div>
      </div>

      {%endif%}
    {%endwith%}
    <div style="margin: 20px;" >
	<form method="POST">
        <h3 align="center">Add Work Details</h3>
        <div class="form-group">
            <label for="name">Work Info</label>
            <input  class="form-control" id="title" name="title" placeholder="Enter your Work Info"/>
            
        </div>
		<div class="form-group">
            <label for="name">Work Id</label>
            <input  class="form-control" id="id" name="id" placeholder="Enter your Work Id"/>
            
        </div>
        <div class="form-group">
          <label for="name">User Name:</label>            
                <input type="text" class="form-control" name="username" id="username" placeholder="Enter your name">
        </div>
        <div class="form-group">
            <label for="name">Info:</label>            
            <input type="text" class="form-control" name="info" id="info" placeholder="Enter your work info">
        </div>
       
		<div class="form-group">
			<label for="name">Deadline:</label>            
            <input type="text" class="form-control" name="deadline" id="deadline" placeholder="Enter your Deadline(yyyy/mm/dd)">
		</div>
    <div class="form-group">
			<label for="name">Status:</label>            
            <select class="form-control" name="status" id="status">
              <option value="status">Select Status Of Your Work</option>
              <option value="request">Request</option>
              <option value="in progress">In Progress</option>
              <option value="review">Review</option>
              <option value="completed">Completed</option>
            </select>  
		</div> 
    <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>


    <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
  <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
</body>
</html>

kanban-todo app/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous"
  />
    <title>
        {% block title %}home{% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class=" navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" >
            <span class="navbar-toggler-icon"></span>
        </button>
    
    <div class="collapse navbar-collapse " id="navbar">
      <div class="navbar-nav">
        {%if user.is_authenticated%}
        <a class="nav-item nav-link" id="home" href="/">Home</a>
        <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
        {%else%}
        <a class="nav-item nav-link" id="login" href="/login">Login</a>
        <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
        {%endif%}
        
      </div>
    </div>
    </nav>
    {%with messages=get_flashed_messages(with_categories=true)%}
      {%if messages%}
        <div class="alert alert-success">
          {%for category, msg in messages%}
            {%if category =='error'%}
              <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{msg}}
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              {%else%}
              <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{msg}}
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            
            {%endif%}
          {%endfor%}
        </div>
      

      {%endif%}
    {%endwith%}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>


    <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
  <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
</body>
</html>

kanban-todo app/website/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kanban Board</title>
    <link rel="stylesheet"  href="/static/style.css">
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous"
  />
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class=" navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" >
        <span class="navbar-toggler-icon"></span>
    </button>

<div class="collapse navbar-collapse " id="navbar">
  <div class="navbar-nav">
    {%if user.is_authenticated%}
        <a class="nav-item nav-link" id="home" href="/add">Add Details</a>
        <a class="nav-item nav-link" id="home" href="/">Home</a>
        <a class="nav-item nav-link" id="login" href="/summary">Summary</a>
        <a class="nav-item nav-link" id="signUp" href="/about">About</a>
		    <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
        {%endif%}

 
  </div>
</div>
</nav>
{%with messages=get_flashed_messages(with_categories=true)%}
{%if messages%}
  <div class="alert alert-success">
    {%for category, msg in messages%}
      {%if category =='error'%}
        <div class="alert alert-danger alter-dismissable fade show" role="alert">
          {{msg}}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {%else%}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
          {{msg}}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
         
        {%endif%}
      {%endfor%}
    </div>
  

  {%endif%}
{%endwith%}
    <h1 style="text-align:center">Kanban Board</h1>
     <div class="container " >
       <div class="hold">
        <h1>Request</h1>
        <ul class="list-group list-group-flush" id="note">
          {% for notes in user.notes %}
          {%if notes.status == "request" %}
          <div class="req" draggable="true">
          <li class="list-group-item">
            <p>
            <div style="background-color:gray;text-align:left;font-size:small">{{ notes.date }}</div>
            <br>
            <div style="text-align:start;font-size:large">{{ notes.title }}</div><br>
            <div style="text-align:start;font-size:medium">{{ notes.id }}</div>
            <div style="text-align:start;font-size:medium">{{ notes.deadline }}</div>
            </p>
           <a href="{{url_for('views.delete',id=notes.id)}}" onclick="return checkdelete()">Delete</a>
           <a href="{{url_for('views.more',id=notes.id)}}">More details</a>
          </li>
          
          </div>
          {% endif %}
          {% endfor %}
        </ul>
       
        </div>
        <div class="hold">
          <h1>In Progress</h1>
        <ul class="list-group list-group-flush" id="note">
          {% for notes in user.notes %}
          {%if notes.status == "in progress" %}
          <div class="req" draggable="true">
          <li class="list-group-item">
            <p>
            <div style="background-color:gray;text-align:left;font-size:small">{{ notes.date }}</div>
            <br>
            <div style="text-align:start;font-size:large">{{ notes.title }}</div><br>
            <div style="text-align:start;font-size:medium">{{ notes.id }}</div>
          </p>
          <a href="{{url_for('views.delete',id=notes.id)}}" onclick="return checkdelete()">Delete</a>
          <a href="{{url_for('views.more',id=notes.id)}}">More details</a>
          </li>
        
        </div>
        {% endif %}
        {% endfor %}
        </ul>
        </div>
        <div class="hold">
          <h1>Review</h1>
        <ul class="list-group list-group-flush" id="note">
          {% for notes in user.notes %}
          {%if notes.status == "review" %}
          <div class="req" draggable="true">
          <li class="list-group-item">
            <p>
            <div style="background-color:gray;text-align:left;font-size:small">{{ notes.date }}</div>
            <br>
            <div style="text-align:start;font-size:large">{{ notes.title }}</div><br>
            <div style="text-align:start;font-size:medium">{{ notes.id }}</div>
          </p>
          <a href="{{url_for('views.delete',id=notes.id)}}" onclick="return checkdelete()">Delete</a>
          <a href="{{url_for('views.more',id=notes.id)}}">More details</a>
        </li>
          
        </div>
        {% endif %}
        {% endfor %}
        </ul>
        </div>
        <div class="hold">
            <h1>Completed</h1>
        <ul class="list-group list-group-flush" id="note">
          {% for notes in user.notes %}
          {%if notes.status == "completed" %}
          <div class="req" draggable="true">
          <li class="list-group-item">
            <p>
            <div id="com" style="background-color:gray;text-align:left;font-size:small">{{ notes.date }}</div>
            <br>
            
            <div style="text-align:start;font-size:large">{{ notes.title }}</div><br>
            <div style="text-align:start;font-size:medium">{{ notes.id }}</div>
            
          </p>
          <a href="{{url_for('views.delete',id=notes.id)}}" onclick="return checkdelete()">Delete</a>
          <a href="{{url_for('views.more',id=notes.id)}}">More details</a>
          </li>
          
        </div>
        {% endif %}
        {% endfor %}
        </ul>
        <div class="popup">
          <div class="pop-box">
            <h2></h2>
          </div>
        </div>
        </div> 
    </div>
    <script src="static/j.js"></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
    <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
  <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  <script>
    function checkdelete(){
      return confirm('Are You Sure You Want To Delete This Card?');
    }
  </script> 
      
      

    
</body>
</html>

kanban-todo app/website/templates/more.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Card</title>
    <link rel="stylesheet"  href="/static/addstyle.css">
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous"
  />
  <script>
    function checkdelete(){
      return confirm('Are You Sure You Want To Delete This Card?');
    }
  </script> 
      
</head>
<body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class=" navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" >
            <span class="navbar-toggler-icon"></span>
        </button>
    
    <div class="collapse navbar-collapse " id="navbar">
      <div class="navbar-nav">
        {%if user.is_authenticated%}
            <a class="nav-item nav-link" id="home" href="/add">Add Details</a>
            <a class="nav-item nav-link" id="home" href="/">Home</a>
            <a class="nav-item nav-link" id="login" href="/summary">Summary</a>
            <a class="nav-item nav-link" id="signUp" href="/about">About</a>
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
            {%endif%}
        
      </div>
    </div>
    </nav>
</header>
<br>
    {% for notes in user.notes %}
    {% if notes.id == id %}
    <div class="container">
        <div class="text">Card Details</div>
        <form action="#">
           <div class="form-row">
              <div class="input-data">
                <label for="">User Name:&nbsp;{{notes.user_name}}</label>
              </div>
              <div class="input-data">
                <label for="">Work Id :&nbsp;{{notes.id}}</label>
              </div>
              <div class="input-data">
                <label for="">Work :&nbsp;{{notes.title}}</label>
              </div>
              <div class="input-data">
                <label for="">Detailed Work Info :&nbsp;{{notes.content}}</label>
              </div>
              <div class="input-data">
                {% if notes.status == 'completed' %}
                <label for="" class="btn btn-success" style="margin:auto">Work Status :&nbsp;Completed</label>
                {%endif%}
                {% if notes.status == 'request' %}
                <label for="" class="btn btn-danger" style="margin:auto">Work Status :&nbsp;Request</label>
                {%endif%}
                {% if notes.status == 'in progress' %}
                <label for="" class="btn btn-warning" style="margin:auto">Work Status :&nbsp;In Progress</label>
                {%endif%}
                {% if notes.status == 'review' %}
                <label for="" class="btn btn-info" style="margin:auto">Work Status :&nbsp; Review</label>
                {%endif%}
              </div>
              <div class="input-data">
                <label for="">Work Posted on :&nbsp;{{notes.date}}</label>
              </div>
              <div class="input-data">
                <label for="b" >Work Deadline :&nbsp;{{notes.deadline}}</label>
              </div>
              {%if notes.com%}
              <div class="input-data">
                <label for="b" >Work Comment :&nbsp;{{notes.com}}</label>
              </div>
              {%endif%}
              
                <br>
                <br>
                <div style="justify-content: center; display: flex;">
              &nbsp;&nbsp;&nbsp;&nbsp;<div id="del" class ="btn btn-danger"><a href="{{url_for('views.delete',id=notes.id)}}" onclick="return checkdelete()">Delete</a></div>&nbsp;&nbsp;&nbsp;
              
              {%if notes.status != 'completed'%}
              &nbsp;&nbsp;&nbsp;&nbsp;<div  class ="btn btn-success" ><a href="{{url_for('views.forw',id=notes.id)}}">Send Forward</a></div>
              {%endif%}
              {%if notes.status != 'request'%}
              &nbsp;&nbsp;&nbsp;&nbsp;<div  class ="btn btn-danger" ><a href="{{url_for('views.back',id=notes.id)}}">Return back</a></div>
              {%endif%}
              <br>
              {%if notes.status=="completed"%}
              &nbsp;&nbsp;&nbsp;&nbsp;<h6>Work Completed On:&nbsp;&nbsp;{{notes.timerem}}&nbsp;&nbsp;&nbsp;{{notes.time}}</h6>
              <br>
              {%endif%}
              
            </div>
              
              
           
           
        </form>
     </div>
     {%if notes.status != 'request' %}
     <div class="form">
     <form method="POST">
       <div class="form-group">
           <label for="name">Comment</label>
           <input  class="form-control" id="comment" name="comment" placeholder="Add A Comment "/>
           
           <button type="submit" class="btn btn-primary">Submit</button>
           <br>
           <br>
           
           <label for="name">Work Title</label>
           <input  class="form-control" id="ip" name="ip" placeholder="Fill If You Want To Update Title "/>
           
           <button type="submit" class="btn btn-primary">Update</button>
          
         </div>
         </form>
     
     </div>
     
     {%endif%}
     {%endif%}
     {% endfor %} 
     
</body>
</html>