BlogLite/views.py
from flask import Blueprint,render_template,request,flash,jsonify,redirect,url_for
from flask_login import login_user,logout_user,current_user
from flask_login import login_required
from models import User,Posts,Comments,Like,Follow
from __init__ import db
from datetime import date,datetime
import json
from sqlalchemy import func, text

views = Blueprint('views', __name__)

@views.route('/create-com/<post_id>',methods=['POST'])
@login_required
def home1(post_id):
    com=request.form.get('text')
        
    
       
    if com:
        post=Posts.query.get_or_404(post_id)
        if post:
            comment=Comments(text=com,post_id=post_id,user_id=current_user.id)
            db.session.add(comment)
            db.session.commit()
            flash("comment added",category="success")
            return redirect(url_for('views.home12'))
        else:
            flash("post doesnot exist",category="error")
            return redirect(url_for('views.home12'))
    else:
        flash("no comment",category="error")
        return redirect(url_for('views.home'))

@views.route('/post',methods=['GET','POST'])
@login_required
def home12():
    posts=Posts.query.all()
    com=Comments.query.all()
    return render_template('post.html',posts=posts,comment=com,user=current_user)

@views.route('/',methods=['GET','POST'])
@login_required
def home():
    posts=Posts.query.filter(Posts.by==current_user.username).all()
    u=current_user.id
    com=Comments.query.filter(Comments.post_id==u).all()
    return render_template('base.html',comments=com,posts=posts,user=current_user)

@views.route('add',methods=['GET','POST'])
@login_required
def add(): 
    if request.method=='POST':
        link=request.form.get('link')
        description=request.form.get('desc')
        title=request.form.get('title')
        
        data=Posts(link=link,title=title,desc=description,by=current_user.username,author=current_user.id)
        db.session.add(data)
        db.session.commit()
        flash("LIST added",category="success")
        return redirect(url_for('views.home'))
    return render_template("home.html",user=current_user)
    
@views.route('/search',methods=['POST'])
@login_required
def search():
    search=request.form.get('searched')
    if len(str(search))>1:
        posts=Posts.query.filter(Posts.by.like('%'+search+'%')).all()
        
        return render_template('search.html',posts=posts,searched=search,user=current_user)
        
    else:
        flash("no search",category="danger")
        return redirect(url_for('views.home'))

@views.route('/profile',methods=['GET','POST'])
@login_required
def pro():
    u=current_user.username
    posts=Posts.query.filter(Posts.by==u).all()
    x=Posts.query.filter(Posts.by==u).count()
    l=Follow.query.all()
    l1=[]
    l2=[]
    for i in l:
        l1.append(i.follower)
        l2.append(i.created_author)
    o=0
    for i in l2:
        if i==u:
            o+=1


    return render_template('profile.html',posts=posts,user=current_user,x=x,y=o)


@views.route('/<int:id>')
@login_required
def delete(id):
    user_to=Posts.query.get_or_404(id)
    if user_to.by != current_user.username:
        flash("not allowed",category="danger")
        return redirect(url_for('views.home'))
    else:
        try:
            db.session.delete(user_to)
            db.session.commit()
            flash("LIST deleted",category="success")
            return redirect(url_for('views.home'))
        except:
            flash("LIST not deleted",category="error")
            return redirect(url_for('views.home'))
    

@views.route('/profile/edit/<int:id>',methods=['GET','POST'])
@login_required
def more(id):
    id1=id
    post=Posts.query.get_or_404(id1) 
    if request.method=='POST':
        
        link=request.form.get('link')
        title=request.form.get('title')
        description=request.form.get('desc')
        if title:
            post.title=title
        elif link:
            post.link=link
        elif description:
            post.desc=description
                     
        db.session.commit()
        flash("LIST added",category="success")
        return redirect(url_for('views.home'))
    return render_template("more.html",user=current_user,post=post)
    
@views.route('/pro1/<int:id>',methods=['GET'])
@login_required
def pro1(id):
    id1=id
    user_to=Posts.query.get(id1)
    if user_to:
        u=user_to.by
        post=Posts.query.filter(Posts.by==u).all()
        x=Posts.query.filter(Posts.by==u).count()
        # print(x)
        l=Follow.query.all()
        l1=[]
        l2=[]
        for i in l:
            l1.append(i.follower)
            l2.append(i.created_author)
        o=0
        for i in l2:
            if i==u:
                o+=1
        
        return render_template('profile1.html',posts=post,user=user_to,x=x,y=o,l1=l1,l2=l2)
    else:
        flash("no Posts availabe",category="error")
        return redirect(url_for('views.home'))
    
@views.route("/delete-comment/<comment_id>")
@login_required
def delete_comment(comment_id):
    comment = Comments.query.filter_by(id=comment_id).first()

    if not comment:
        flash('Comment does not exist.', category='error')
    elif current_user.id != comment.user_id and current_user.id != comment.post.author:
        flash('You do not have permission to delete this comment.', category='error')
    else:
        db.session.delete(comment)
        db.session.commit()

    return redirect(url_for('views.home12'))



@views.route("/like-post/<post_id>", methods=['POST'])
@login_required
def like(post_id):
    post = Posts.query.filter_by(id=post_id).first()
    like = Like.query.filter_by(
        author=current_user.id, post_id=post_id).first()

    if not post:
        return jsonify({'error': 'Post does not exist.'}, 400)
    elif like:
        db.session.delete(like)
        db.session.commit()
    else:
        like = Like(author=current_user.id, post_id=post_id)
        db.session.add(like)
        db.session.commit()
    
    return redirect(url_for('views.home'))
    
@views.route("/follow/<id>", methods=['GET','POST'])
@login_required
def follow(id):
    l=Follow.query.all()
    l1=[]
    l2=[]
    print(l)
    for i in l:
        
        l1.append(i.follower)
        l2.append(i.created_author)

    
    print(l1)
    print(l2)
    post = Posts.query.filter_by(id=id).first()
    print(post.by)
    print(current_user.username )
    if ((current_user.username not in l1) or (post.by not in l2)):    
        data=Follow(created_author=post.by,author=post.author,post_id=id,follower=current_user.username)
        db.session.add(data)
        db.session.commit()
    s='views.pro1/'+str(id)
    return redirect(url_for('views.pro1',id=id,l1=l1,l2=l2))

@views.route("/unfollow/<id>", methods=['GET','POST'])
@login_required
def unfollow(id):
    c=current_user.username
    deli=Follow.query.filter_by(follower=c).first()
    # print(deli)
    db.session.delete(deli)
    db.session.commit()

    s='views.pro1/'+str(id)
    return redirect(url_for('views.pro1',id=id))

BlogLite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous"
      />
      <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous"
      />
    <title>
        Home
    </title>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">BLogLite</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {%if user.is_authenticated%}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
              Options
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/post">Posts</a></li>
              <li><a class="dropdown-item" href="/profile">Profile</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="/logout">Logout</a></li>
            </ul>
          </li>
          
        </ul>
        
      </div>
    </div>


      <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
    
  </nav>
  {%endif%}
    <div>
      {%with messages=get_flashed_messages(with_categories=true)%}
      {%if messages%}
        <div class="alert alert-success">
          {%for category, msg in messages%}
            {%if category =='error'%}
              <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{msg}}
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              {%else%}
              <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{msg}}
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            
            {%endif%}
          {%endfor%}
        </div>
      </div>
      

      {%endif%}
    {%endwith%}
    
      <div class="container my-5" >
        <div class="row align-items-start">
        <div class="col">
          
          {%if posts|length !=0%}
            {%for post in posts%}
            {%if user.username == post.by %}
            <div class="card my-3" style="width: 25rem;">
              {%if post.link|length!=0%}
                <img src="{{post.link}}" class="card-img-top" alt="...">
              
              {%endif%}
              
              <div class="card-body">
                <a href="/profile">{{post.by}}</a>
                <h3 class="card-text">{{post.title }}</h3>
                <h4 class="card-text">{{post.desc }}</h4>
                
                  <a href="{{url_for('views.delete',id=post.id)}}" onclick="return checkdelete()" class="btn btn-primary">Delete</a>
                  <a href="{{url_for('views.more',id=post.id)}}" class="btn btn-primary">Update</a>
                {%endif%}
              </div>
              {%endfor%}
              {%endif%}
              
              {%if posts.id==comments.post_id %}
              
              <div class="card-body">
                <br />
                <div class="collapse" id="comments-{{posts.id}}">
                  <div class="card">
                    <div class="card-body" id="comments-expanded-{{posts.id}}">
                      {% for comment in comments %}
                     
                      <div class="d-flex justify-content-between align-items-center">
                        <div>
                          <a href="/pro1/{{comment.user_id}}"
                            >{{comment.user.username}}</a
                          >: {{comment.text}}
                        </div>
                        <div>
                          <br>
                          <small class="text-muted"> {{comment.date}}</small>
                          {%if user.username == comment.user.username%}
                          <div class="btn-group">
                            <button
                              type="button"
                              class="btn btn-sm btn-primary dropdown-toggle"
                              data-bs-toggle="dropdown"
                            ></button>
                            <ul class="dropdown-menu">
                              <li>
                                <a
                                  href="/delete-comment/{{comment.id}}"
                                  class="dropdown-item"
                                  >Delete</a
                                >
                                <br>
                              </li>
                            </ul>
                          </div>
                          {%endif%}
                        </div>
                      </div>
                      
                      
                      {% endfor %}
                      {%endif%}
                      
                    </div>
                  </div>
                </div>
                <p class="card-text">
                  {% if comments|length > 0 %}
                  <a data-bs-toggle="collapse" href="#comments-{{posts.id}}" role="button">
                    <small>View {{comments|length}} Comments</small>
                  </a>
                  {% else %}
                  <small class="text-muted">No Comments</small>
                  {% endif %}
                </p>
                
            </div>
            
         
          <div class="alert alert-dark" role="alert">
            No Posts Yet!
          </div>
          

        </div>
        <div class="col">
         <p>Didnt start posting Yet! Wanna Post</p>
         <a href="add" class="btn btn-primary">Post</a>
        </div>
        </div>
      </div>

    <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
  <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
    <script>
      function checkdelete(){
        return confirm('Are You Sure You Want To Delete This Card?');
      }
    </script> 
</body>
</html>

BlogLite/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous"
      />
      <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous"
      />
    <title>
        Profile
    </title>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">BLogLite</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {%if user.is_authenticated%}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
              Options
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/post">Posts</a></li>
              
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="/logout">Logout</a></li>
            </ul>
          </li>
          
        </ul>
        
      </div>
    </div>


      <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
    
  </nav>
  {%endif%}
    <div>
      {%with messages=get_flashed_messages(with_categories=true)%}
      {%if messages%}
        <div class="alert alert-success">
          {%for category, msg in messages%}
            {%if category =='error'%}
              <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{msg}}
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              {%else%}
              <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{msg}}
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            
            {%endif%}
          {%endfor%}
        </div>
      </div>
      

      {%endif%}
    {%endwith%}
      <div class="container my-5">
        <div class="row align-items-start">
        <div class="col">
          
          {%if posts|length !=0%}
            {%for post in posts%}
            {%if user.username == post.by %}
            <div class="card my-3" style="width: 18rem;">
              {%if post.link|length!=0%}
                <img src="{{post.link}}" class="card-img-top" alt="...">
              
              {%endif%}
              
              <div class="card-body">
                <p>{{post.by}}</p>
                <p class="card-text">{{post.title }}</p>
                <p class="card-text">{{post.desc }}</p>
                <p class="card-text">Posted on : {{post.date}}</p>
                <p class="card-text">Likes : {{post.likes|length}}</p>
                <p class="card-text">Comments : {{post.comments|length}}</p>
                {%for po in post.comments%}
                <p class="card-text">Comments : {{po.text}}</p>
                {%endfor%}
                  <a href="{{url_for('views.delete',id=post.id)}}" class="btn btn-primary" onclick="return checkdelete()">Delete</a>
                  <a href="{{url_for('views.more',id=post.id)}}" class="btn btn-primary" >Update </a>
                {%endif%}
              </div>
            </div>
            {%endfor%}  
          {%else%}
          <div class="alert alert-dark" role="alert">
            No Posts Yet!
          </div>
          {%endif%}

        </div>
        <div class="col">
         <p>Didnt start posting Yet! Wanna Post</p>
         <a href="add" class="btn btn-primary">Post</a>
        </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Profile</h5>
                <p class="card-text">UserName:&ensp;{{user.username}}</p>
                <p class="card-text">Number of Post:&ensp;{{x}}</p>
                <p class="card-text">Number of Followers: {{y}}</p>
                
              </div>
            </div>
          </div>
         
      </div>

    <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
  <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
    <script>
      function checkdelete(){
        return confirm('Are You Sure You Want To Delete This Card?');
      }
    </script> 
</body>
</html>

BlogLite/templates/profile1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous"
      />
      <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous"
      />
    <title>
        Profile
    </title>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">BLogLite</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
              Options
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/post">Posts</a></li>
              
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="/logout">Logout</a></li>
            </ul>
          </li>
          
        </ul>
        
      </div>
    </div>


      <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
     
    
    
  </nav>
  
    <div>
      <div>
      {%with messages=get_flashed_messages(with_categories=true)%}
      {%if messages%}
        <div class="alert alert-success">
          {%for category, msg in messages%}
            {%if category =='error'%}
              <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{msg}}
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              {%else%}
              <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{msg}}
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            
            {%endif%}
          {%endfor%}
        </div>
      </div>
      

      {%endif%}
    {%endwith%}
    </div>
    <div>
      <div class="container my-5">
        <div class="row align-items-start">
        <div class="col">
          
          {%if posts|length !=0%}
            {%for post in posts%}
            
            <div class="card my-3" style="width: 25rem;">
              {%if post.link|length!=0%}
                <img src="{{post.link}}" class="card-img-top" alt="...">
              
              
              <div class="card-body">
                <p>{{post.by}}</p>
                <p class="card-text">{{post.title}}</p>
                <p class="card-text">{{post.desc }}</p>
                <p class="card-text">Posted on : {{post.date }}</p>
                <p class="card-text">Likes : {{post.likes|length}}</p>
                <p class="card-text">Comments : {{post.comments|length}}</p>
                {%for po in post.comments%}
                <p class="card-text">Comments : {{po.text}}</p>
                {%endfor%}
                <div>
                  {%if current_user.username is in l1 and post.by is in l2%}
                  <a href="{{url_for('views.unfollow',id=post.id)}}" id="follow" class="btn btn-secondary" onclick="follow()">Unfollow</a>
                  {%else%}
                  <a href="{{url_for('views.follow',id=post.id)}}" id="follow"class="btn btn-primary" onclick="follow()">Follow</a>
                  {%endif%}
                </div>
                
                {%endif%}
              </div>
            </div>
            {%endfor%}  
          {%else%}
          <div class="alert alert-dark" role="alert">
            No Posts Yet!
          </div>
          {%endif%}
         
        </div>
       
      <div class="container">
        <div class="row">
          <div class="col">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Profile</h5>
                <p class="card-text">UserName: {{user.by}}</p>
                <p class="card-text">Number of Post: {{x}}</p>
                <p class="card-text">Number of Followers: {{y}}</p>
                
              </div>
            </div>
          </div>
         
      </div>
      </div>
    </div>
      </div>
    </div>

    <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
  <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
    <script>
      function checkdelete(){
        return confirm('Are You Sure You Want To Delete This Card?');
      }
    </script> 
    <script>
      function follow(){
        if ("{{current_user.username}}" in "{{ll}}" ){
          document.getElementById("follow").innerHTML = "Following";
          document.getElementById("follow").style.backgroundColor = "gray";
        }
        else{
          document.getElementById("follow").style.backgroundColor = "blue";
          document.getElementById("follow").innerHTML = "Follow";
        }
      }
    </script>
</body>
</html>